language: php

php:
  - 5.4
  - 5.5

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer install

script:
    - mkdir -p build/logs
    - bin/phpunit -c phpunit.xml.dist

after_script:
    - bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
    - php bin/coveralls -v
